services:
  redis:
    image: redis:7-alpine
    container_name: mlops_redis

  app:
    build: .
    container_name: mlops_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # Shared volume
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: mlops_worker
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # Shared volume
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis